const FETCH_DETAILS = "product/FETCH_DETAILS";
const FETCH_DETAILS_COMPLETED = "product/FETCH_DETAILS_COMPLETED";
const FETCH_DETAILS_FAILED = "product/FETCH_DETAILS_FAILED";

const FETCH_LIST = "product/FETCH_LIST";
const FETCH_LIST_COMPLETED = "product/FETCH_LIST_COMPLETED";
const FETCH_LIST_FAILED = "product/FETCH_LIST_FAILED";

export default {
    FETCH_DETAILS,
    FETCH_DETAILS_COMPLETED,
    FETCH_DETAILS_FAILED,
    FETCH_LIST,
    FETCH_LIST_COMPLETED,
    FETCH_LIST_FAILED,
};
