const LOGIN = "session/LOGIN";
const LOGIN_COMPLETED = "session/LOGIN_COMPLETED";
const LOGIN_FAILED = "session/LOGIN_FAILED";
const LOGOUT = "session/LOGOUT";
const INITIALIZE = "sesstion/INITIALIZE_SESSION";
const SET_REDIRECT_AFTER_LOGIN = "session/SET_REDIRECT_AFTER_LOGIN";

export default {
    LOGIN,
    LOGIN_COMPLETED,
    LOGIN_FAILED,
    LOGOUT,
    INITIALIZE,
    SET_REDIRECT_AFTER_LOGIN,
};
