const LOGIN = "LOGIN";
const LOGIN_COMPLETED = "LOGIN_COMPLETED";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGOUT = "LOGOUT";
const INITIALIZE_SESSION = "INITIALIZE_SESSION";
const SET_REDIRECT_AFTER_LOGIN = "SET_REDIRECT_AFTER_LOGIN";

export default {
    LOGIN,
    LOGIN_COMPLETED,
    LOGIN_FAILED,
    LOGOUT,
    INITIALIZE_SESSION,
    SET_REDIRECT_AFTER_LOGIN,
};
